name: Maven Packages

on:
  push:
    paths:
      - java/**
    branches:
      - master
  pull_request:
    paths:
      - java/**
    branches:
      - master
  workflow_dispatch:

jobs:
  build-publish:
    strategy:
      matrix:
        include:
          - path: "java/Streaming"
          - path: "java/S3Sink"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: ${{ matrix.path }}
      run: mvn package -Denforcer.skip=true

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

