name: Maven Packages

on:
  push:
    paths:
      - java/**
      - .github/workflows/maven_packages.yml
#    branches:
#      - master

  pull_request:
    paths:
      - java/**
#    branches:
#      - master

  workflow_dispatch:

jobs:
  build-publish:
    strategy:
      matrix:
        include:
          - path: "java/Streaming"
          - path: "java/S3Sink"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      working-directory: ${{ matrix.path }}
      run: mvn --batch-mode package

    - name: Publish to GitHub Packages Apache Maven
      working-directory: ${{ matrix.path }}
      run: mvn --batch-mode deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

